### ISSUE TITLE
When searching for Black moves amoeba gives positive evaluation when other engines report negative.

### ISSUE THREAD

**Issue by dejlek** [abulmo/amoeba#10]
Not sure this is a bug or not, but I have noticed slight difference at how amoeba reports evaluation compared to Stockfish and Fire (Anscacs for an example behaves like Amoeba - it gives positive evaluations).

When you do MultiPV of say 4 and `position startpos moves g2g4` for an example, amoeba gives positive evaluation of typically 70+ centipawns. However, the abovementioned engines will report -70+ centipawns.

Is this a potential bug or not?

**Comment by abulmo** [comment]
I do not have the same results.
With stockfish 8, this is what I got:
```
info depth 20 seldepth 35 multipv 1 score cp 73 nodes 28542670 nps 1659554 hashfull 999 tbhits 0 time 17199 pv e7e5 e2e3 d7d5 d2d4 b8c6 b1c3 e5d4 e3d4 f8b4 f1g2 g8e7 h2h3 h7h5 e1f1 c8e6 a2a3 b4a5 g4h5 e7f5 g1f3 h8h5
info depth 20 seldepth 35 multipv 2 score cp 66 nodes 28542670 nps 1659554 hashfull 999 tbhits 0 time 17199 pv d7d5 e2e3 e7e5 d2d4 b8c6 b1c3 g8f6 h2h3 f8b4 d4e5 b4c3 b2c3 f6e4 g1f3 h7h5 h1g1 h5g4 h3g4 f7f6 f1b5 e8g8 b5c6 b7c6
info depth 20 seldepth 35 multipv 3 score cp 62 nodes 28542670 nps 1659554 hashfull 999 tbhits 0 time 17199 pv b8c6 c2c4 e7e5 b1c3 f8b4 c3d5 g8e7 e2e3 d7d6 d5b4 c6b4 d2d4 e5d4 e3d4 d6d5 c1e3 c8e6 d1a4 b4c6 g1f3 e6g4
info depth 20 seldepth 35 multipv 4 score cp 54 nodes 28542670 nps 1659554 hashfull 999 tbhits 0 time 17199 pv c7c5 c2c4 d7d5 c4d5 d8d5 g1f3 c8g4 b1c3 d5f5 f1g2 b8c6 d2d3 e7e5 h2h3 g4h5 c1e3 e8c8 c3e4 c5c4 e4g3 f5g6 e1g1 h5d3 g2f3
```
With amoeba, I got a similar output:
```
info depth 20 seldepth 34 multipv 1 score cp 62 nps 1554716 time 21352 nodes 33197825 hashfull 322 pv d7d5 h2h3 e7e5 f1g2 b8c6 d2d3 c8e6 e2e4 h7h5 b1c3 d5e4 g2e4 h5g4 h3g4 h8h1 e4h1 d8h4 h1c6 b7c6 d1f3 e8c8 
info depth 20 seldepth 30 multipv 2 score cp 53 nps 1554716 time 21352 nodes 33197825 hashfull 322 pv e7e5 c2c4 d7d5 c4d5 d8d5 g1f3 c8g4 b1c3 d5d6 d1a4 g4d7 a4c4 c7c5 d2d3 b8c6 f3g5 g8h6 f1g2 d6d4 c3d5 f8e7 
info depth 20 seldepth 35 multipv 3 score cp 45 nps 1554716 time 21352 nodes 33197825 hashfull 322 pv b8c6 d2d4 d7d5 h2h3 h7h5 g4g5 e7e5 d4e5 c6e5 b1c3 c8e6 g1f3 e5f3 e2f3 d5d4 c3e4 f7f5 e4g3 h5h4 f1b5 c7c6 d1e2 
info depth 20 seldepth 33 multipv 4 score cp 39 nps 1554716 time 21352 nodes 33197825 hashfull 322 pv c7c5 h2h3 d7d5 c2c4 e7e6 f1g2 b8c6 d2d3 h7h5 b1c3 d5d4 c3e4 g8f6 g4g5 f6e4 g2e4 c8d7 c1d2 f8d6 g1f3 
```
With Fire 6.1 I also got positive results for black here.

According to those engines, g2g4 looks like a bad opening move, so a positive value for Black is fine. Some programs (Crafty, for example) always return scores as white point of view, but Amoeba, as many other engines, return scores with the player to move point of view.  Some graphical interfaces allow to modify the point of view. TCEC  for example uses the white point of view to display scores.  Are you sure the settings of your graphical interface are the same for all the engines?

**Comment by dejlek** [comment]
I was actually confused by negative evaluation for `position startpos moves e2e4` but then Stockfish guys explained that engine evaluates the move from perspective of that particular side (Black or White). So it makes sense that the engine is going to evaluate first few replies to 1.e4 in negative numbers, because it is  Black's move...
