### ISSUE TITLE
postmortem freezes when -H option is in use

### ISSUE THREAD

**Issue by dejlek** [abulmo/amoeba#11]
First I want to say that `postmortem` is an amazing tool! Thanks!
I wanted to give it a larger hash size (between 16 and 24 G) as my workstation has plenty of RAM, but then it runs forever... Without the -H it works fine.

**Comment by abulmo** [comment]
Thank you for your interest.
I cannot reproduce your problem. Do you have the complete command line, so I can figure out what is going on?

**Comment by dejlek** [comment]
I used to test with `postmortem -H 4096 -c 6 -d 22 -f lasker_vs_herzfeld_1895.pgn`

**Comment by dejlek** [comment]
Note, the old code works for an example with -H 2048 because the calculated value (in bytes) is still within the `int` range of values.
