### ISSUE TITLE
Amoeba suddenly plays bad move 

### ISSUE THREAD

**Issue by tissatussa** [abulmo/amoeba#17]
while testing in CuteChess, Amoeba v3.3.1 (which i compiled on Linux 64 bit) plays a strange move which lost a piece : 

![amoeba_strange_move](https://user-images.githubusercontent.com/1109281/132398609-aa838dcf-6fbd-47fe-9ce1-4b620010b348.png)

Rd1 after 6.3 seconds ?!  What happened ?  In 1 other game Amoeba had the same issue, suddenly giving a Rook ..

**Comment by abulmo** [comment]
Sorry for the late response.
I am aware of this problem. I hope to have fixed it in version 3.4, but I need to examine more game to be sure. Well, Amoeba will still play poorly from time to time, but no obvious blunder like this, hopefully.
