### ISSUE TITLE
weekly snapshot: une version officielle de Amoeba?

### ISSUE THREAD

**Issue by ChessGUI** [abulmo/amoeba#7]
Est-ce que l´édition du quatrième février 2017 une version officielle? Pour ça j´ai  une demande de renseignements présente  en langue anglaise (ComputerChess Wiki)

**Comment by abulmo** [comment]
Non, il s'agit d'une extraction hebdomadaire de la version en cours de développement. Amoeba a très peu changé par rapport à la version 2.1. J'ai plus travaillé sur le gestionnaire de tournoi que sur Amoeba pour l'instant. Peut-être il y aura une version 2.2 courant mars/avril, mais je ne pense pas avant.
